### ISSUE TITLE
0.57.4 HvacState: CQRS state extraction failed

### ISSUE THREAD

**Issue by silverailscolo** [ramses-rf/ramses_cc#749]
After update to 0.57.4 via HACS, this error appears in System > Logs (summarized):

```
Logger: ramses_rf.pipeline.ingestion
Bron: runner.py:289
Eerst voorgekomen: 06:50:00 (3 gebeurtenissen)
Laatst gelogd: 06:54:43

CQRS state extraction failed for src 37:153226: HvacState.__init__() got an unexpected keyword argument 'req_reason'. Did you mean 'request_reason'?

CQRS state extraction failed for dst 18:130140: HvacState.__init__() got an unexpected keyword argument 'req_reason'. Did you mean 'request_reason'?

```

Same errors after a reboot of HA.

System log fragment:

```
2026-06-28 06:50:00.620 INFO (MainThread) [ramses_tx.protocol.base] Recv'd: 000 RQ --- 18:130140 37:153226 --:------ 2210 001 00

2026-06-28 06:50:00.642 INFO (MainThread) [ramses_tx.transport.mqtt] mq Tx: {"msg": "RQ --- 18:000730 29:099029 --:------ 2210 001 00"}

2026-06-28 06:50:00.668 INFO (MainThread) [ramses_tx.protocol.base] Recv'd: 060 RP --- 37:153226 18:130140 --:------ 2210 042 00FF00FFFFFF0000000000FFFFFFFFFF00FFFFFF0000000000FFFFFFFFFFFFFFFF000000000000000140

2026-06-28 06:50:00.683 INFO (MainThread) [ramses_rf.dispatcher] ||  37:153226 |  18:130140 | RP | unknown_2210     |  00  || {'exhaust_fan_speed': None, 'req_reason': 'IDL', 'unknown_78': '00', 'unknown_80': '01', 'unknown_82': '40'}

2026-06-28 06:50:00.683 ERROR (MainThread) [ramses_rf.pipeline.ingestion] CQRS state extraction failed for src 37:153226: HvacState.__init__() got an unexpected keyword argument 'req_reason'. Did you mean 'request_reason'?

2026-06-28 06:50:00.684 ERROR (MainThread) [ramses_rf.pipeline.ingestion] CQRS state extraction failed for dst 18:130140: HvacState.__init__() got an unexpected keyword argument 'req_reason'. Did you mean 'request_reason'?
```

**Comment by silverailscolo** [comment]
@PWhite-Eng This might be simple to fix in _rf

https://github.com/ramses-rf/ramses_rf/blob/master/src/ramses_rf/pipeline/ingestion.py#L389-L390

**Comment by PWhite-Eng** [comment]
Hi @silverailscolo, thanks for providing the clear logs
We've tracked this down to a mapping mismatch in the CQRS ingestion pipeline. The parser was outputting the reason code using the internal constant SZ_REQ_REASON (which is "req_reason"), but the HvacState domain model explicitly requires the full property name "request_reason".
Rather than changing the parser (which would have broken downstream systems that rely on "req_reason"), we've updated the ingestion boundary layer to safely translate the key before updating the state model. While investigating this, we also found and fixed a related silent bug preventing HVAC filter remaining days/percentages from hydrating correctly
I have raised PR ramses-rf/ramses_rf#743 to address this, and it should stop the log spam and restore your HVAC state updates.

**Comment by silverailscolo** [comment]
Fixed in PR mentioned just above, will be in 0.57.5
