### ISSUE TITLE
0.59.1: `send_packet` action unavailable

### ISSUE THREAD

**Issue by Deathbyteacup** [ramses-rf/ramses_cc#864]
**Describe the bug**

Fixed in 0.59.1: 
Calling the `ramses_cc.send_packet` service in 0.59.0 fails immediately with `AttributeError: 'CommandDTO' object has no attribute 'src'`. This appears to affect all `send_packet` calls regardless of payload content, since the failing code path (`_adjust_sentinel_packet`) is called unconditionally on every `CommandDTO` before any value comparison happens. 

This started immediately after upgrading to 0.59.0; a previously working "keep alive" automation that sends faked zone-temperature packets to a BDR91 relay now fails every time it runs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Developer tools > Actions
2. Select the `ramses_cc.send_packet` action
3. Switch to YAML mode and run:

```yaml
action: ramses_cc.send_packet
data:
  device_id: "03:004303"
  from_id: "03:004303"
  verb: I
  code: 30C9
  payload: "000834"
```

4. See the error in Settings > System > Logs

**Expected behaviour**
The service call should build and transmit the packet as it did prior to 0.59.0, without raising an exception.

```
File "/config/custom_components/ramses_cc/init.py", line 435, in async_send_packet
await _coordinator.async_send_packet(call)
File "/config/custom_components/ramses_cc/coordinator.py", line 2473, in async_send_packet
await self.service_handler.async_send_packet(call)
File "/config/custom_components/ramses_cc/services.py", line 372, in async_send_packet
self._adjust_sentinel_packet(cmd)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
File "/config/custom_components/ramses_cc/services.py", line 397, in _adjust_sentinel_packet
if cmd.src.id != "18:000730" or cmd.dst.id != hgi.id:
^^^^^^^
AttributeError: 'CommandDTO' object has no attribute 'src'
```

**Screenshots**
N/A

**Additional context**
- Installed version of Ramses RF integration: 0.59.0 (also using `ramses_rf` 0.59.0 as pinned by this release)
- Gateway dongle: nanoCUL clone (CH340/FTDI-based USB-to-RF dongle running evofw3), connected via `/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0`
- Gateway interface: USB (serial), not MQTT
- Custom settings: `known_list` includes a faked `THM` device (`03:004303`, `faked: true`) used to send periodic faked zone-temperature (`30C9`) packets via `send_packet`, to keep a `BDR` relay (`13:006094`) in sync with desired heating state
- `enforce_known_list: true`, `advanced_features.send_packet: true`
- Regression appears introduced by the `CommandDTO` migration in #853 ("Migrate to CommandDTO and stabilise test suite for ramses_rf#877 compatibility") — `_adjust_sentinel_packet` in `services.py` line 397 still references `cmd.src`/`cmd.dst`, which no longer exist on the new `CommandDTO` object
- Workaround: rolled back to 0.58.x via HACS, which restores `send_packet` functionality

**Comment by wimpie70** [comment]
Thank you. I'll have a look.

**Comment by silverailscolo** [comment]
@Deathbyteacup Can you check this is fixed in Ramses RF 0.59.1?

**Comment by pocketware** [comment]
Updated to 0.59.1 because of testing https://github.com/ramses-rf/ramses_cc/issues/871 and also to fix this issue.

Still having an issue on sending a ~send_package~ send_packet command.
Error in HA:

<img width="691" height="77" alt="Image" src="https://github.com/user-attachments/assets/212fd6ac-c45b-45ab-943b-b42ba329b183" />


Action YAML:

```yaml
action: ramses_cc.send_packet
metadata: {}
data:
  device_id: '32:161205'
  from_id: '37:126467'
  verb: W
  code: '2411'
  payload: 00004B0000000000020000000000000002000000010000
```

**Comment by silverailscolo** [comment]
I can use the `send_packet` Action without errors on HVAC. Are you sure there are no errors setting up Actions during startup? Here occasionally the Action disappears after some other instruction crashes it.

Restart HA and run your script to check.
Check your HA system log for errors mentioning "send_packet".

**Comment by pocketware** [comment]
Also after a reboot there is no ramses_cc.send_packet

<img width="1825" height="829" alt="Image" src="https://github.com/user-attachments/assets/f22a34e6-11d0-4594-87f3-436a87e0f6f5" />

Can't find anything in the logs with "send_packet"

**Comment by silverailscolo** [comment]
> Also after a reboot there is no ramses_cc.send_packet
> 
> <img width="1825" height="829" alt="Image" src="https://github.com/user-attachments/assets/f22a34e6-11d0-4594-87f3-436a87e0f6f5" />
> 
> Can't find anything in the logs with "send_packet"

Please turn on Debug logging in Ramses RF integration pane top right), restart and attach the detailed system log here (drag it to the edit comment pane.

**Comment by pocketware** [comment]
[home-assistant_ramses_cc_2026-07-29T11-29-23.578Z.log](https://github.com/user-attachments/files/30503055/home-assistant_ramses_cc_2026-07-29T11-29-23.578Z.log)

**Comment by silverailscolo** [comment]
Thanks for the log. Two errors in your system log, close together, related to hvac_ventilator device `32:161205`:

```
2026-07-29 13:28:32.699 DEBUG (MainThread) [custom_components.ramses_cc.number] No value available for parameter 4C
2026-07-29 13:28:32.699 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/ramses_cc/number.py", line 850, in _request_parameter_value
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1017, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>
2026-07-29 13:28:32.710 DEBUG (MainThread) [ramses_rf.devices.hvac_ventilators] Parameter 88 not found for 32:161205
2026-07-29 13:28:32.710 DEBUG (MainThread) [custom_components.ramses_cc.number] Got value None for parameter 88 from device 32:161205 store
2026-07-29 13:28:32.711 DEBUG (MainThread) [custom_components.ramses_cc.number] No value available for parameter 88
2026-07-29 13:28:32.711 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/ramses_cc/number.py", line 850, in _request_parameter_value
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1017, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>
2026-07-29 13:28:32.724 DEBUG (MainThread) [ramses_rf.devices.hvac_ventilators] Parameter DA not found for 32:161205
2026-07-29 13:28:32.725 DEBUG (MainThread) [custom_components.ramses_cc.number] Got value None for parameter DA from device 32:161205 store
2026-07-29 13:28:32.725 DEBUG (MainThread) [custom_components.ramses_cc.number] No value available for parameter DA
2026-07-29 13:28:32.725 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/config/custom_components/ramses_cc/number.py", line 850, in _request_parameter_value
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1017, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>
2026-07-29 13:28:32.728 INFO (MainThread) [custom_components.ramses_cc.coordinator] Saving the client state cache (packets, schema)
```

Must ask @wimpie70 to check what is happening (regards 2411 params).

**Comment by PWhite-Eng** [comment]
Investigated the `RuntimeError: Attribute hass is None` log errors reported during startup:

### Root Cause
When entity creation runs during platform setup, `_request_parameter_value()` is scheduled as a background task immediately after `async_add_entities()`. In Home Assistant, `hasattr(self, "hass")` evaluates to `True` on `Entity` subclasses even when `self.hass` is `None` prior to entity registration. Consequently, `_request_parameter_value()` proceeded to call `self.async_write_ha_state()`, raising an unhandled `RuntimeError` that caused background initialisation task failures.

### Resolution
1. Added an explicit `self.hass is None` guard in `_request_parameter_value()` to exit cleanly if the entity is not yet attached to Home Assistant.
2. Triggered `_request_parameter_value()` inside `async_added_to_hass()` once `self.hass` is guaranteed to be set.
3. Added unit test coverage for null `hass` handling and `async_added_to_hass()` parameter requests in `test_number.py`.

A pull request has been opened to resolve this issue: ramses-rf/ramses_cc#872.

**Comment by PWhite-Eng** [comment]
Hi @silverailscolo,

Regarding the two errors noted for device `32:161205`:

When `ramses_rf` returns `None` for uncached parameters (such as `4C`, `88`, `DA`), `RamsesNumberParam._request_parameter_value()` enters its `else:` branch and calls `self.async_write_ha_state()`.

Because parameter requests are scheduled asynchronously during platform setup immediately following `async_add_entities()`, Home Assistant has not yet attached `self.hass` to the entity. Calling `self.async_write_ha_state()` while `self.hass` is `None` raises `RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>`.

The explicit `self.hass is None` check introduced in PR ramses-rf/ramses_cc#872 guards against premature state writes when `get_fan_param()` returns `None`, resolving both error instances.

**Comment by wimpie70** [comment]
## Root cause analysis: persisting QosProtocol timeout for W|01FF on HGI80

Following up on @maartenv86's comment (Jul 27) about the `QosProtocol` send timeout for `W|01FF` to an Itho device — the `AttributeError` from the original issue 864 was fixed by PR 867, but the timeout is a separate symptom with a different root cause.

### Investigation findings

The `W|01FF` timeout on HGI80 gateways has **three contributing factors**, two of which are fixable software bugs addressed in ramses_rf PR 967:

**Bug A — `_patch_cmd_if_needed` missing reverse-patch for HGI80**: The HGI80 firmware requires `18:000730` as the source address for frames it transmits. If `from_id` was the actual gateway ID, the HGI80 silently dropped the frame — no echo, QoS FSM times out.

**Bug B — echo suppression mismatch + strip bug**: PR 957's `_is_recent_tx` didn't account for HGI80 address substitution in echoes, and `_log_tx_packet` used `strip()` which broke I/W verb frame parsing.

**Hardware limitation**: The HGI80 may not support `01FF` at all (tracked in [ramses_rf issue 73](https://github.com/ramses-rf/ramses_rf/issues/73)).

### References

- ramses_rf PR 967 (fixes): https://github.com/ramses-rf/ramses_rf/pull/967
- ramses_rf issue 835 (QosProtocol timeout): https://github.com/ramses-rf/ramses_rf/issues/835
- ramses_rf issue 73 (01FF not understood): https://github.com/ramses-rf/ramses_rf/issues/73
- ramses_rf PR 957 (echo suppression): https://github.com/ramses-rf/ramses_rf/pull/957

**Comment by wimpie70** [comment]
## Update: PR #867 ref + root cause analysis

Following up on @maartenv86's [comment](https://github.com/ramses-rf/ramses_cc/issues/835#issuecomment-5026495751) in #835 (Jul 27) about the `QosProtocol` send timeout for `W|01FF` to an Itho device — the `AttributeError` from the original issue 864 was fixed by PR 867 (https://github.com/ramses-rf/ramses_cc/pull/867), but the timeout is a separate symptom with a different root cause.

### Investigation findings

The `W|01FF` timeout on HGI80 gateways has **three contributing factors**, two of which are fixable software bugs addressed in ramses_rf PR 967:

**Bug A — `_patch_cmd_if_needed` missing reverse-patch for HGI80**: The HGI80 firmware requires `18:000730` as the source address for frames it transmits. If `from_id` was the actual gateway ID, the HGI80 silently dropped the frame — no echo, QoS FSM times out.

**Bug B — echo suppression mismatch + strip bug**: PR 957's `_is_recent_tx` didn't account for HGI80 address substitution in echoes, and `_log_tx_packet` used `strip()` which broke I/W verb frame parsing.

**Hardware limitation**: The HGI80 may not support `01FF` at all (tracked in ramses_rf issue 73).

### References

- ramses_cc PR 867 (original AttributeError fix): https://github.com/ramses-rf/ramses_cc/pull/867
- ramses_rf PR 967 (new fixes): https://github.com/ramses-rf/ramses_rf/pull/967
- ramses_rf issue 835 (QosProtocol timeout): https://github.com/ramses-rf/ramses_rf/issues/835
- ramses_rf issue 73 (01FF not understood): https://github.com/ramses-rf/ramses_rf/issues/73
- ramses_rf PR 957 (echo suppression): https://github.com/ramses-rf/ramses_rf/pull/957

**Comment by silverailscolo** [comment]
@Deathbyteacup Is this fixed and available again in pre-release 0.59.3?

**Comment by Deathbyteacup** [comment]
@silverailscolo confirming the issue is resolved in 0.59.3 - many thanks for your efforts on this.

**Comment by maartenv86** [comment]
@wimpie70 I'm trying to change the thermostat at 0.59.3 and it took some time but now different errors appear:

`W --- 21:057310 18:002965 --:------ 22D0 008 0014001E14030020 < Payload doesn't match W/22D0: 0014001E14030020 != ^03[0-9]{4}1E14030020$

|| 18:000730 | 21:057310 | W | unknown_01FF | 00 || {'temperature': None, 'setpoint_bounds': (20.0, None), 'time_planning': False, 'temp_adjusted': False, '_flags_10': 'D0'} < DeviceNotFoundError(Can't create 18:000730: it is not an allowed device_id (if required, add it to the known_list))

|| 21:057310 | | I | unknown_3EF0 | 02 || {'modulation_level': 0.0, '_flags_2': '00', '_flags_3': [0, 0, 0, 1, 0, 0, 0, 0], 'ch_active': False, 'dhw_active': False, 'cool_active': True, 'flame_on': False, '_unknown_4': '02', '_unknown_5': '00'} < PacketInvalid( I --- 21:057310 --:------ 21:057310 3EF0 006 020000100200 < Unexpected verb/code for src (THM) to Tx)`

Binding is at the moment not working yet but I need to do more testing. I'm using the blueprint from Onl1ne1373 in HA.

**Comment by wimpie70** [comment]
@silverailscolo can you reopen this again ?
