### ISSUE TITLE
0.58.3: Orcon HRC-400 fan lost 15 entities

### ISSUE THREAD

**Issue by wesleymooiman** [ramses-rf/ramses_cc#851]
Title: FAN loses configuration entities after upgrading from 0.57.12 to 0.58.3

Description

After upgrading from 0.57.12 to 0.58.3, my Orcon HRC-400 FAN device loses a significant number of entities.

0.57.12: ~40 entities
0.58.3: ~25 entities

Around 15 entities disappear, including all configuration/setting entities such as the comfort temperature and other configurable FAN settings.

What I tried
Cleared the Home Assistant entity/device cache.
Allowed auto-discovery to recreate all entities from scratch.
Removed and rebuilt the entity scheme.

None of these steps made any difference. The configuration entities are simply no longer exposed in 0.58.3.

Verification

To rule out a Home Assistant issue, I downgraded back to 0.57.12 (after restoring the previous entity scheme, since the new one is not backwards compatible).

Immediately after downgrading, all missing entities returned and everything worked as expected again.

Hardware
Unit: Orcon HRC-400 (GRU 400)
Integration version: Works on 0.57.12, broken on 0.58.3.

**Comment by wimpie70** [comment]
@wesleymooiman - Thanks for reporting. It seems the 2411 params are broken. I'll find a fix. A new release is expected on/after thursday.

```
2026-07-20 10:42:01.756 DEBUG (MainThread) [custom_components.ramses_cc.services] Processing update_fan_params service call with data: {'device_id': ['32:153289']}
2026-07-20 10:42:01.757 DEBUG (MainThread) [custom_components.ramses_cc.services] Processing get_fan_param service call with data: {'device_id': '32:153289', 'param_id': '01'}
2026-07-20 10:42:01.757 DEBUG (MainThread) [ramses_rf.devices.hvac_ventilators] Found bound REM device 37:168270 for FAN 32:153289
2026-07-20 10:42:01.759 DEBUG (MainThread) [custom_components.ramses_cc.fan_handler] Found entity number.32_153289_param_01 in entity registry
2026-07-20 10:42:01.764 DEBUG (MainThread) [custom_components.ramses_cc.services] Sending command: CommandDTO(verb=<VerbT.RQ: 'RQ'>, addr1='37:168270', addr2='32:153289', addr3='--:------', code=<Code._2411: '2411'>, payload='000001', priority=<Priority.DEFAULT: 0>, num_repeats=0)
2026-07-20 10:42:01.827 ERROR (MainThread) [custom_components.ramses_cc.services] Failed to get fan parameter: 'CommandDTO' object has no attribute 'src'
Traceback (most recent call last):
  File "/config/custom_components/ramses_cc/services.py", line 369, in async_get_fan_param
    await self._coordinator.client.async_send_cmd(cmd)
  File "/usr/local/lib/python3.14/site-packages/ramses_rf/gateway.py", line 461, in async_send_cmd
    return await self._engine.async_send_cmd(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/ramses_tx/engine.py", line 364, in async_send_cmd
    return await self._protocol.send_cmd(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.14/site-packages/ramses_tx/protocol/core.py", line 310, in send_cmd
    cmd = self._patch_cmd_if_needed(cmd)
  File "/usr/local/lib/python3.14/site-packages/ramses_tx/protocol/base.py", line 299, in _patch_cmd_if_needed
    and cmd.src.id == HGI_DEV_ADDR.id
        ^^^^^^^
AttributeError: 'CommandDTO' object has no attribute 'src'
2026-07-20 10:42:01.877 ERROR (MainThread) [custom_components.ramses_cc.services] Failed to get fan parameter 01 for device: Failed to get fan parameter: 'CommandDTO' object has no attribute 'src'
2026-07-20 10:42:01.877 DEBUG (MainThread) [custom_components.ramses_cc.services] Processing get_fan_param service call with data: {'device_id': '32:153289', 'param_id': '31'}
2026-07-20 10:42:01.877 DEBUG (MainThread) [ramses_rf.devices.hvac_ventilators] Found bound REM device 37:168270 for FAN 32:153289
2026-07-20 10:42:01.877 DEBUG (MainThread) [custom_components.ramses_cc.fan_handler] Found entity number.32_153289_param_31 in entity registry
2026-07-20 10:42:01.877 DEBUG (MainThread) [custom_components.ramses_cc.services] Sending command: CommandDTO(verb=<VerbT.RQ: 'RQ'>, addr1='37:168270', addr2='32:153289', addr3='--:------', code=<Code._2411: '2411'>, payload='000031', priority=<Priority.DEFAULT: 0>, num_repeats=0)
2026-07-20 10:42:01.877 ERROR (MainThread) [custom_components.ramses_cc.services] Failed to get fan parameter: 'CommandDTO' object has no attribute 'src'
Traceback (most recent call last):
```

**Comment by silverailscolo** [comment]
Fixes in 0.59.0. Feel free to reopen issue if still not working in 0.59.0

**Comment by Kars-de-Jong** [comment]
@silverailscolo Not working for me on Orcon HRC-400 with version 0.59.2:

- All configuration entities are Unavailable.
- Fan mode, Fan rate, Filter remaining and Filter remaining (%) entities are Unknown.

No errors or warnings logged.

**Comment by wimpie70** [comment]
I found the regression. The initial 2411 discovery msg is no longer (since 0.59.x) sent, so the other config entries are no longer requested. I'll propose a fix for this.
I can't see the fan mode, fan rate, filter remaining, - (%) entities unknown, so that's hard to analyze, but will try...

**Comment by silverailscolo** [comment]
@Kars-de-Jong Can you check out 0.59.4 and report here?

**Comment by ilijaNL** [comment]
Got the same problem with Orcon, tested on ramses_cc 0.59.2 and 0.59.4. 

Logs saying this:

```
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.coordinator] Platform setup completed for number
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Processing 5 items
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] create_parameter_entities for 32_155471
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Device 32_155471 does not support 2411 parameters, skipping parameter entities
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] create_parameter_entities for 37_168272
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Device 37_168272 does not support 2411 parameters, skipping parameter entities
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] create_parameter_entities for 29_181233
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Device 29_181233 does not support 2411 parameters, skipping parameter entities
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] create_parameter_entities for 29_181234
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Device 29_181234 does not support 2411 parameters, skipping parameter entities
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] create_parameter_entities for 18_156980
2026-08-14 20:33:56.745 DEBUG (MainThread) [custom_components.ramses_cc.number] Device 18_156980 does not support 2411 parameters, skipping parameter entities
2026-08-14 20:33:56.745 INFO (MainThread) [custom_components.ramses_cc.coordinator] Saving the client state cache (packets, schema)
```

Schema:

```yaml
"18:156980":
  _class: HGI
  _owner: me
"29:181233":
  _class: CO2
  _faked: true
  _owner: me
"29:181234":
  _class: CO2
  _faked: true
  _owner: me
"32:155471":
  _bound: "37:168272"
  _class: FAN
  _commands:
    _comment: Commands on FAN (Phase 3b) — target this entity for automations
    auto:
      code: 22F1
      payload: "000407"
      verb: I
    auto2:
      code: 22F1
      payload: "000507"
      verb: I
    away:
      code: 22F1
      payload: "000007"
      verb: I
    boost:
      code: 22F1
      payload: "000607"
      verb: I
    bypass_auto:
      code: 22F7
      payload: 00FFEF
      verb: W
    bypass_close:
      code: 22F7
      payload: 0000EF
      verb: W
    bypass_open:
      code: 22F7
      payload: 00C8EF
      verb: W
    disable:
      code: 22F1
      payload: "000707"
      verb: I
    high:
      code: 22F1
      payload: "000307"
      verb: I
    high_15:
      code: 22F3
      payload: 00120F03040404
      verb: I
    high_30:
      code: 22F3
      payload: 00121E03040404
      verb: I
    high_60:
      code: 22F3
      payload: 00123C03040404
      verb: I
    low:
      code: 22F1
      payload: "000107"
      verb: I
    med_60:
      code: 22F3
      payload: 00123C02040404
      verb: I
    medium:
      code: 22F1
      payload: "000207"
      verb: I
    request10D0:
      code: 10D0
      payload: "00"
      verb: RQ
    request31DA:
      code: 31DA
      payload: "00"
      verb: RQ
    reset_filter:
      code: 10D0
      payload: 00FF
      verb: W
  _owner: me
  _scheme: orcon
  remotes:
    - "37:168272"
"37:168272":
  _class: REM
  _commands:
    _comment: Commands on REM (Phase 3a) — will be deprecated, use FAN instead
    auto: " I --- 37:168272 32:155471 --:------ 22F1 003 000407"
    auto2: " I --- 37:168272 32:155471 --:------ 22F1 003 000507"
    away: " I --- 37:168272 32:155471 --:------ 22F1 003 000007"
    boost: " I --- 37:168272 32:155471 --:------ 22F1 003 000607"
    bypass_auto: " W --- 37:168272 32:155471 --:------ 22F7 003 00FFEF"
    bypass_close: " W --- 37:168272 32:155471 --:------ 22F7 003 0000EF"
    bypass_open: " W --- 37:168272 32:155471 --:------ 22F7 003 00C8EF"
    disable: " I --- 37:168272 32:155471 --:------ 22F1 003 000707"
    high: " I --- 37:168272 32:155471 --:------ 22F1 003 000307"
    high_15: " I --- 37:168272 32:155471 --:------ 22F3 007 00120F03040404"
    high_30: " I --- 37:168272 32:155471 --:------ 22F3 007 00121E03040404"
    high_60: " I --- 37:168272 32:155471 --:------ 22F3 007 00123C03040404"
    low: " I --- 37:168272 32:155471 --:------ 22F1 003 000107"
    med_60: " I --- 37:168272 32:155471 --:------ 22F3 007 00123C02040404"
    medium: " I --- 37:168272 32:155471 --:------ 22F1 003 000207"
    request10D0: RQ --- 37:168272 32:155471 --:------ 10D0 001 00
    request31DA: RQ --- 37:168272 32:155471 --:------ 31DA 001 00
    reset_filter: " W --- 37:168272 32:155471 --:------ 10D0 002 00FF"
  _faked: true
  _owner: me
_owner: me
orphans_hvac:
  - "29:181233"
  - "29:181234"
  - "32:155471"

```

**Comment by wimpie70** [comment]
the discover 2411 params was removed in 0.58.3
I'll create a fix, but this may be temporary....
We also have a 6 hour poll, but we need the initial discovery for this to work.

**Comment by Kars-de-Jong** [comment]
@silverailscolo With 0.59.4 it all seems fine again. Yesterday I installed 0.59.5 which broke something else: my template entities based on the `event.ramses_cc_regex_event` trigger. But that has nothing to do with this issue.
