### ISSUE TITLE
How to switch 0.56.0/.1/.2 versions

### ISSUE THREAD

**Issue by silverailscolo** [ramses-rf/ramses_cc#601]
Since 0.56.3 the configuration format was updated to v2.

The following steps to switch to earlier releases from 0.56.1/0.56.2 were [provided](https://github.com/ramses-rf/ramses_cc/issues/583#issuecomment-4207994089) by @peternash

> Switching back and forth between Ramses RF versions is a little more complex now so I'll note it here in case anyone else is doing the same.

## 0.56.0 <> 0.56.1
Transitioning between <=0.56.0 and >=0.56.1 in either direction requires that the Packet Log config is saved. The integration will fail to load until this is done.

## Down from 0.56.2
Transitioning from >=0.56.2 to <= 0.56.1 (in that direction only) will raise an error and the integration will fail to load.
Clearing the "System state (recent packets)" cache _only_ will allow the integration to load.
It's important not to clear the "Discovered system (schema)" cache as the schema won't rebuild on 0.56.x at the moment.

## Down from 0.56.3
Warning: this is more difficult, because the config VERSION was increased to 2.

Download the version you want in HACS and delete `.storage/ramses_cc`. It clears the cache but discovery works on 0.54.3 so not a problem.

We are working on a patched `__init.py__` that you copy to your local HA setup using the File Editor app (to add the required downgrade function).

**Comment by wimpie70** [comment]
Not sure if this was posted elsewhere too, but it might help:
On 0.56.3 I did get this error:

```
2026-04-09 10:16:30.939 ERROR (MainThread) [custom_components.ramses_cc] Unexpected error during setup of entry 01KKP880DFBBWJTQHME175WF5V: set_pkt_logging() got an unexpected keyword argument 'rotate_backups'
```

**Fix**:

Ramses RF would not load until:
- go to configuration
- go to Packet log
- Submit
- restart and RF will load again

**Comment by silverailscolo** [comment]
> Not sure if this was posted elsewhere

Yes, that essentially is our instruction in https://github.com/ramses-rf/ramses_cc/issues/592
